{% set version = "2.3.0" %}

package:
  name: libidn2
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/libidn/libidn2-{{ version }}.tar.gz
  sha256: e1cb1db3d2e249a6a3eb6f0946777c2e892d5c5dc7bd91c74394fc3a01cab8b5

build:
{% if bootstrapping == 'yes' %}
  # Please increment by two
  number: 0
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_bootstrapping
{% else %}
  # Keep above the number of the _bootstrapping package
  number: 1
{% endif %}
  skip: True  # [win]
  run_exports:
    # _Amazing_ backwards compatibility so pin to major number:
    #    https://abi-laboratory.pro/tracker/timeline/libidn2/
    - {{ pin_subpackage('libidn2', min_pin='x', max_pin='x') }}
  script_env:
    - BOOTSTRAPPING={{ bootstrapping }}

requirements:
  build:
    - {{ compiler('c') }}
{% if bootstrapping != 'yes' %}
    - make
    - pkg-config
  host:
    - gettext
    - libunistring
{% endif %}

test:
  commands:
    - test -f "${PREFIX}/include/idn2.h"
    - test -f "${PREFIX}/lib/libidn2${SHLIB_EXT}"

about:
  home: "https://www.gnu.org/software/libidn/#libidn2"
  license: LGPLv2
  license_file: COPYING
  summary: "Library for internationalized domain names (IDNA2008) support"

extra:
  recipe-maintainers:
    - hmaarrfk
    # This recipe I got from
    # - chenghlee
