{% set version = "2.0.5" %}

package:
  name: libidn2
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/libidn/libidn2-{{ version }}.tar.gz
  sha256: 53f69170886f1fa6fa5b332439c7a77a7d22626a82ef17e2c1224858bb4ca2b8

build:
  skip: True  # [win]
  number: 1
  run_exports:
    # _Amazing_ backwards compatibility so pin to major number:
    #    https://abi-laboratory.pro/tracker/timeline/libidn2/
    - {{ pin_subpackage('libidn2', min_pin='x', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - test -f "${PREFIX}/include/idn2.h"
    - test -f "${PREFIX}/lib/libidn2${SHLIB_EXT}"

about:
  home: "https://www.gnu.org/software/libidn/#libidn2"
  license: LGPLv2
  license_file: COPYING
  summary: "Library for internationalized domain names (IDNA2008) support"

extra:
  recipe-maintainers:
    - hmaarrfk
    # This recipe I got from
    # - chenghlee
